# Generated by Django 4.2.15 on 2024-08-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=50, verbose_name='نام کامل'),
        ),
    ]
