# Generated by Django 6.0.5 on 2026-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_notification_is_global_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_sms_to_all',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک به همه کاربران'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_error',
            field=models.TextField(blank=True, verbose_name='شرح خطای پیامک'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_recipients_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دریافت\u200cکنندگان پیامک'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیامک'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_status',
            field=models.CharField(choices=[('not_requested', 'درخواستی ثبت نشده'), ('pending', 'در انتظار ارسال'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='not_requested', max_length=20, verbose_name='وضعیت ارسال پیامک'),
        ),
    ]
