# Generated by Django 6.0.5 on 2026-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_notification_send_sms_to_all_notification_sms_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sms_status',
            field=models.CharField(choices=[('not_requested', 'درخواستی ثبت نشده'), ('pending', 'در انتظار ارسال'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], db_index=True, default='not_requested', max_length=20, verbose_name='وضعیت ارسال پیامک'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='account_not_created_f5a86f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='account_not_user_id_18fc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_global', 'created_at'], name='account_not_is_glob_206dff_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sms_status', 'created_at'], name='account_not_sms_sta_827f95_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['token', 'code'], name='account_otp_token_5e3c80_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'created_at'], name='account_otp_phone_d1cba9_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['created_at'], name='account_otp_created_4f7c10_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='account_use_phone_664a69_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['fullname'], name='account_use_fullnam_9e64f2_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'created_at'], name='account_use_user_id_2469b4_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key', 'created_at'], name='account_use_session_fc32dc_idx'),
        ),
    ]
