# Generated by Django 4.2.15 on 2026-06-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_notification_sms_status_alter_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date_jalali',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='گروه خونی'),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='قد (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='وزن (کیلوگرم)'),
        ),
    ]
