# Generated by Django 6.0.5 on 2026-06-13 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_user_birth_date_jalali_user_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='نام نمایشی'),
        ),
        migrations.CreateModel(
            name='BodyCircumferenceMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور مچ دست')),
                ('forearm_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ساعد')),
                ('arm_rest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور بازو در حالت استراحت')),
                ('arm_flexed_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور بازو در حالت انقباض')),
                ('head_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور سر')),
                ('neck_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور گردن')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور قفسه سینه')),
                ('shoulders_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور شانه\u200cها')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور کمر')),
                ('abdomen_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور شکم')),
                ('hips_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور باسن')),
                ('thigh_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ران پا')),
                ('calf_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ساق پا')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circumference_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اندازه\u200cگیری محیط بدن',
                'verbose_name_plural': 'اندازه\u200cگیری\u200cهای محیط بدن',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaliperMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_armpit_men_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='چین پوستی بین نوک سینه و زیربغل')),
                ('axilla_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ناحیه زیر بغل')),
                ('subscapular_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='زیر استخوان کتف')),
                ('abdominal_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کنار ناو')),
                ('suprailiac_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='بالای لگن کنار شکم')),
                ('chest_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='زیر سینه')),
                ('biceps_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عضله جلو بازو')),
                ('triceps_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='پشت بازو')),
                ('thigh_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='جلوی ران')),
                ('calf_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='پشت ساق پا')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caliper_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اندازه\u200cگیری کالیپر',
                'verbose_name_plural': 'اندازه\u200cگیری\u200cهای کالیپر',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='client_media/images/', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='client_media/videos/', verbose_name='ویدیو')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_media', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فایل کاربر',
                'verbose_name_plural': 'فایل\u200cهای کاربر',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
