# Generated by Django 4.2.15 on 2026-06-23 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام عضله')),
                ('origin', models.TextField(blank=True, verbose_name='مبدا')),
                ('insertion', models.TextField(blank=True, verbose_name='انتها')),
                ('nerve', models.CharField(blank=True, max_length=120, verbose_name='عصب')),
                ('function_note', models.TextField(blank=True, verbose_name='عملکرد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='muscles/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'عضله',
                'verbose_name_plural': 'کتابخانه عضلات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='arm_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='طول بازو'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='elbow_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض آرنج'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='hip_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض لگن'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='knee_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض زانو'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='shoulder_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض شانه'),
        ),
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'کم\u200cتحرک (کمتر از ۵۰۰۰ قدم در روز)'), ('low_active', 'کم\u200cفعال (۵۰۰۰ تا ۷۵۰۰ قدم در روز)'), ('moderate_active', 'نسبتاً فعال (۷۵۰۰ تا ۱۰۰۰۰ قدم در روز)'), ('active', 'فعال (۱۰۰۰۰ تا ۱۲۵۰۰ قدم در روز)'), ('high_active', 'بسیار فعال (بیش از ۱۲۵۰۰ قدم در روز)')], max_length=20, null=True, verbose_name='سطح فعالیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to=settings.AUTH_USER_MODEL, verbose_name='مربی'),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='client_media/documents/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'برنامه/فایل کاربر',
                'verbose_name_plural': 'برنامه\u200cها و فایل\u200cهای کاربر',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام حرکت')),
                ('body_part', models.CharField(choices=[('upper', 'بالاتنه'), ('lower', 'پایین\u200cتنه')], max_length=10, verbose_name='بخش بدن')),
                ('movement_type', models.CharField(choices=[('push', 'هل دادن'), ('pull', 'کشیدن'), ('leg', 'پا'), ('core', 'مرکزی بدن'), ('full_body', 'تمام بدن')], max_length=12, verbose_name='نوع حرکت')),
                ('joint_type', models.CharField(choices=[('single', 'تک\u200cمفصلی'), ('multi', 'چندمفصلی')], max_length=10, verbose_name='نوع مفصل')),
                ('power_type', models.CharField(choices=[('power', 'پاورلیفتینگ'), ('strength', 'قدرتی')], max_length=10, verbose_name='نوع قدرت')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=15, verbose_name='سطح دشواری')),
                ('equipment_type', models.CharField(choices=[('bodyweight', 'وزن بدن'), ('free_weight', 'وزنه آزاد'), ('fixed_machine', 'دستگاه ثابت'), ('cable', 'کابل'), ('band', 'کش'), ('other', 'سایر')], max_length=15, verbose_name='تجهیزات')),
                ('media', models.FileField(blank=True, null=True, upload_to='exercises/', verbose_name='تصویر یا ویدیو')),
                ('primary_muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_exercises', to='account.muscle', verbose_name='عضله اصلی')),
                ('secondary_muscle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_exercises', to='account.muscle', verbose_name='عضله فرعی')),
            ],
            options={
                'verbose_name': 'حرکت تمرینی',
                'verbose_name_plural': 'کتابخانه حرکات تمرینی',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['primary_muscle'], name='account_exe_primary_92dec9_idx'), models.Index(fields=['body_part'], name='account_exe_body_pa_3f4848_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoachRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_per_week', models.CharField(choices=[('1', '۱ جلسه در هفته'), ('2', '۲ جلسه در هفته'), ('3', '۳ جلسه در هفته'), ('4', '۴ جلسه در هفته'), ('5', '۵ جلسه در هفته'), ('6', '۶ جلسه در هفته'), ('coach_discretion', 'هر چه مربی صلاح بداند')], max_length=20, verbose_name='تعداد جلسات در هفته')),
                ('wants_diet', models.BooleanField(default=False, verbose_name='درخواست برنامه غذایی')),
                ('wants_workout', models.BooleanField(default=False, verbose_name='درخواست برنامه تمرینی')),
                ('pain_notes', models.TextField(blank=True, verbose_name='درد یا آسیب')),
                ('illness_notes', models.TextField(blank=True, verbose_name='بیماری زمینه\u200cای')),
                ('diet_restrictions', models.TextField(blank=True, verbose_name='محدودیت\u200cهای غذایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('handled', 'بررسی شده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست از مربی',
                'verbose_name_plural': 'درخواست\u200cهای از مربی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='account_coa_status_60eed2_idx'), models.Index(fields=['user', 'created_at'], name='account_coa_user_id_6b9cea_idx')],
            },
        ),
    ]
