# Generated by Django 4.2.15 on 2026-06-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_exercise_finalize_lookup_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='arm_flexed_left_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور بازو در حالت انقباض (چپ)'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='arm_rest_left_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور بازو در حالت استراحت (چپ)'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='forearm_left_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ساعد (چپ)'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='قد (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='measured_at_jalali',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ثبت اندازه\u200cگیری (شمسی)'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='وزن (کیلوگرم)'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='wrist_left_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور مچ دست (چپ)'),
        ),
        migrations.AddField(
            model_name='calipermeasurement',
            name='measured_at_jalali',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ثبت اندازه\u200cگیری (شمسی)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='نام انگلیسی حرکت'),
        ),
    ]
