# Generated by Django 4.2.15 on 2026-06-24 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def split_fullname_into_first_last(apps, schema_editor):
    User = apps.get_model('account', 'User')
    for user in User.objects.exclude(fullname=''):
        parts = user.fullname.rsplit(' ', 1)
        if len(parts) == 2:
            first_name, last_name = parts
        else:
            first_name, last_name = parts[0], ''
        User.objects.filter(pk=user.pk).update(first_name=first_name, last_name=last_name)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_extend_admin_portal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='leg_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='طول پا'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='sit_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='قد نشسته'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_note_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='تجهیزات اجرا (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_note_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='تجهیزات اجرا'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pressure_type',
            field=models.CharField(blank=True, choices=[('time', 'زمان\u200cمحور'), ('weight', 'وزنه\u200cمحور'), ('time_weight', 'زمان و وزنه'), ('reps', 'تکرارمحور (بدون وزنه/زمان)')], max_length=20, verbose_name='نوع فشار'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps_count',
            field=models.CharField(blank=True, max_length=20, verbose_name='تعداد تکرار'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps_goal',
            field=models.CharField(blank=True, max_length=80, verbose_name='هدف تکرار'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_goal',
            field=models.CharField(blank=True, max_length=80, verbose_name='هدف استراحت'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_minutes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='زمان استراحت (دقیقه)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_movement_type_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='نوع حرکت دوم (انگلیسی)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_movement_type_fa',
            field=models.CharField(blank=True, max_length=60, verbose_name='نوع حرکت دوم'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد ست'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets_goal',
            field=models.CharField(blank=True, max_length=80, verbose_name='هدف ست'),
        ),
        migrations.AddField(
            model_name='exercisebodypart',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='exercisedifficultylevel',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='exerciseequipmenttype',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='exercisejointtype',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='exercisemovementtype',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='exercisepowertype',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='نام خانوادگی'),
        ),
        migrations.RunPython(split_fullname_into_first_last, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='calipermeasurement',
            name='abdominal_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='شکم'),
        ),
        migrations.AlterField(
            model_name='calipermeasurement',
            name='biceps_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='جلوبازو'),
        ),
        migrations.AlterField(
            model_name='calipermeasurement',
            name='chest_armpit_men_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='سینه'),
        ),
        migrations.AlterField(
            model_name='calipermeasurement',
            name='suprailiac_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='سه\u200cتیغ خاصره'),
        ),
        migrations.CreateModel(
            name='BirthdaySmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.CharField(max_length=10, verbose_name='تاریخ ارسال (شمسی)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ارسال پیامک تبریک تولد',
                'verbose_name_plural': 'ارسال\u200cهای پیامک تبریک تولد',
                'unique_together': {('user', 'sent_on')},
            },
        ),
    ]
