# Generated by Django 4.2.15 on 2026-06-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_extend_admin_portal_round3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAbnormalityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='ناهنجاری')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'ناهنجاری',
                'verbose_name_plural': 'انواع ناهنجاری',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseExecutionEquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نوع تجهیزات اجرایی')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'نوع تجهیزات اجرایی',
                'verbose_name_plural': 'انواع تجهیزات اجرایی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSecondaryMovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نوع حرکت دوم')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'نوع حرکت دوم',
                'verbose_name_plural': 'انواع حرکت دوم',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment_note_en',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment_note_fa',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps_count',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps_goal',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rest_goal',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rest_minutes',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_movement_type_en',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_movement_type_fa',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets_count',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets_goal',
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات حرکت'),
        ),
        migrations.AddField(
            model_name='muscle',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='نام انگلیسی عضله'),
        ),
        migrations.AlterField(
            model_name='calipermeasurement',
            name='axilla_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='زیربغل'),
        ),
        migrations.AlterField(
            model_name='calipermeasurement',
            name='chest_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='کمر'),
        ),
        migrations.AlterField(
            model_name='calipermeasurement',
            name='subscapular_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='تحت کتفی'),
        ),
        migrations.CreateModel(
            name='CorrectiveExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام حرکت')),
                ('media', models.FileField(blank=True, null=True, upload_to='corrective_exercises/', verbose_name='تصویر یا ویدیو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('abnormality_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrective_exercises', to='account.exerciseabnormalitytype', verbose_name='نوع ناهنجاری')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrective_exercises', to='account.exerciseequipmenttype', verbose_name='تجهیزات مورد نیاز')),
            ],
            options={
                'verbose_name': 'حرکت اصلاحی',
                'verbose_name_plural': 'کتابخانه حرکات اصلاحی',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='execution_equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='account.exerciseexecutionequipmenttype', verbose_name='نوع تجهیزات اجرایی'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_movement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='account.exercisesecondarymovementtype', verbose_name='نوع حرکت دوم'),
        ),
    ]
