# Generated by Django 4.2.15 on 2026-06-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_corrective_exercises_and_gym_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePressureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نوع فشار')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'نوع فشار',
                'verbose_name_plural': 'انواع فشار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseRepetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.CharField(max_length=40, verbose_name='تعداد تکرار')),
                ('goal', models.CharField(blank=True, max_length=80, verbose_name='هدف')),
            ],
            options={
                'verbose_name': 'نوع تکرار',
                'verbose_name_plural': 'انواع تکرار',
                'ordering': ['goal', 'reps'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseRestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_time', models.CharField(max_length=40, verbose_name='زمان استراحت')),
                ('goal', models.CharField(blank=True, max_length=80, verbose_name='هدف')),
            ],
            options={
                'verbose_name': 'نوع استراحت',
                'verbose_name_plural': 'انواع استراحت',
                'ordering': ['goal', 'rest_time'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_count', models.CharField(max_length=40, verbose_name='تعداد ست')),
                ('goal', models.CharField(blank=True, max_length=80, verbose_name='هدف')),
            ],
            options={
                'verbose_name': 'نوع ست',
                'verbose_name_plural': 'انواع ست',
                'ordering': ['goal', 'set_count'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نوع ورزش')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='نام انگلیسی')),
            ],
            options={
                'verbose_name': 'نوع ورزش',
                'verbose_name_plural': 'انواع ورزش',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='calf_left_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ساق پا (چپ)'),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bodycircumferencemeasurement',
            name='thigh_left_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ران پا (چپ)'),
        ),
        migrations.AddField(
            model_name='calipermeasurement',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='pressure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='account.exercisepressuretype', verbose_name='نوع فشار'),
        ),
    ]
