# Generated by Django 4.2.15 on 2026-06-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_legacy_import_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachrequest',
            name='abdomen_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور شکم'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='arm_flexed_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور بازو منقبض'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='arm_rest_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور بازو آزاد'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='calf_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ساق پا'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='chest_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور سینه'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='forearm_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ساعد'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='قد (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='hips_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور باسن'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='pushed_to_measurements',
            field=models.BooleanField(default=False, verbose_name='به اندازه\u200cگیری\u200cها افزوده شد'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='shoulders_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور سرشانه'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='thigh_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ران'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='waist_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور کمر'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='وزن (کیلوگرم)'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='wrist_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور مچ دست'),
        ),
        migrations.CreateModel(
            name='CoachRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='coach_requests/', verbose_name='فایل پیوست')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='account.coachrequest')),
            ],
            options={
                'verbose_name': 'پیوست درخواست مربی',
                'verbose_name_plural': 'پیوست\u200cهای درخواست مربی',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
