# Generated by Django 5.1.15 on 2026-07-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_decimal_height_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachrequest',
            name='calf_left_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ساق پا (چپ)'),
        ),
        migrations.AddField(
            model_name='coachrequest',
            name='thigh_left_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور ران (چپ)'),
        ),
    ]
