# Generated by Django 4.2.15 on 2026-09-01 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_coachrequest_calf_left_cm_coachrequest_thigh_left_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان برنامه')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_published', models.BooleanField(default=True, verbose_name='نمایش برای کاربر')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات برنامه')),
                ('supplements_note', models.TextField(blank=True, verbose_name='مکمل و نکات تغذیه\u200cای')),
                ('warmup_notes', models.TextField(blank=True, verbose_name='توضیحات گرم کردن')),
                ('cooldown_notes', models.TextField(blank=True, verbose_name='توضیحات سرد کردن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_workout_programs', to=settings.AUTH_USER_MODEL, verbose_name='تجویزکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_programs', to=settings.AUTH_USER_MODEL, verbose_name='ورزشکار')),
            ],
            options={
                'verbose_name': 'برنامه بدنسازی',
                'verbose_name_plural': 'برنامه\u200cهای بدنسازی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='عنوان روز')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات روز')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='account.workoutprogram', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'روز برنامه بدنسازی',
                'verbose_name_plural': 'روزهای برنامه بدنسازی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgramCorrective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('warmup', 'حین گرم کردن'), ('cooldown', 'حین سرد کردن')], max_length=20, verbose_name='مرحله اجرا')),
                ('sets', models.CharField(blank=True, max_length=40, verbose_name='تعداد ست')),
                ('reps', models.CharField(blank=True, max_length=60, verbose_name='تکرار/مدت')),
                ('note', models.TextField(blank=True, verbose_name='نکته')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('corrective_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_items', to='account.correctiveexercise', verbose_name='حرکت اصلاحی')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_items', to='account.workoutprogram', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'حرکت اصلاحی برنامه',
                'verbose_name_plural': 'حرکت\u200cهای اصلاحی برنامه',
                'ordering': ['phase', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.CharField(max_length=40, verbose_name='تعداد ست')),
                ('reps', models.CharField(max_length=60, verbose_name='تعداد تکرار')),
                ('rest', models.CharField(blank=True, max_length=40, verbose_name='استراحت')),
                ('note', models.TextField(blank=True, verbose_name='نکته حرکتی')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.workoutprogramday', verbose_name='روز برنامه')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_items', to='account.exercise', verbose_name='حرکت اصلی')),
                ('superset_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superset_program_items', to='account.exercise', verbose_name='حرکت دوم سوپرست')),
            ],
            options={
                'verbose_name': 'حرکت برنامه بدنسازی',
                'verbose_name_plural': 'حرکت\u200cهای برنامه بدنسازی',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['day', 'order'], name='account_wor_day_id_003c63_idx'), models.Index(fields=['exercise'], name='account_wor_exercis_a9392d_idx'), models.Index(fields=['superset_exercise'], name='account_wor_superse_eab6e6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workoutprogramday',
            constraint=models.UniqueConstraint(fields=('program', 'order'), name='unique_workout_program_day_order'),
        ),
        migrations.AddIndex(
            model_name='workoutprogramcorrective',
            index=models.Index(fields=['program', 'phase', 'order'], name='account_wor_program_96201d_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutprogramcorrective',
            index=models.Index(fields=['corrective_exercise'], name='account_wor_correct_7a46c2_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutprogram',
            index=models.Index(fields=['user', 'is_published', 'start_date'], name='account_wor_user_id_10c19e_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutprogram',
            index=models.Index(fields=['prescribed_by', 'created_at'], name='account_wor_prescri_d4461e_idx'),
        ),
    ]
