# Generated by Django 5.1.15 on 2026-09-01 09:30

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0052_workoutprogramexercise_third_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutProgramFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="سطح دشواری",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="زمان ثبت بازخورد",
                    ),
                ),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_feedback",
                        to="account.workoutprogram",
                        verbose_name="برنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازخورد برنامه بدنسازی",
                "verbose_name_plural": "بازخوردهای برنامه بدنسازی",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPerformanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repetitions",
                    models.CharField(
                        max_length=60,
                        verbose_name="تعداد تکرار برنامه",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("weight", "وزنه (کیلوگرم)"),
                            ("body_weight", "وزن بدن"),
                            ("time", "زمان (ثانیه)"),
                        ],
                        max_length=20,
                        verbose_name="نحوه ثبت عملکرد",
                    ),
                ),
                (
                    "set_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="شماره ست",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مقدار ثبت‌شده",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="زمان ایجاد",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="آخرین به‌روزرسانی",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workout_performance_records",
                        to="account.exercise",
                        verbose_name="حرکت",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_records",
                        to="account.workoutprogram",
                        verbose_name="برنامه",
                    ),
                ),
                (
                    "program_exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_records",
                        to="account.workoutprogramexercise",
                        verbose_name="حرکت برنامه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_performance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ورزشکار",
                    ),
                ),
            ],
            options={
                "verbose_name": "رکورد عملکرد حرکت",
                "verbose_name_plural": "رکوردهای عملکرد حرکت",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "exercise", "mode"],
                        name="account_wor_user_id_7f94d8_idx",
                    ),
                    models.Index(
                        fields=["user", "exercise", "repetitions"],
                        name="account_wor_user_id_090abb_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "exercise", "repetitions", "mode", "set_number"),
                        name="unique_workout_performance_record",
                    ),
                    models.CheckConstraint(
                        check=models.Q(value__gt=0),
                        name="workout_performance_value_positive",
                    ),
                ],
            },
        ),
    ]
