# Generated by Django 5.1.15 on 2026-09-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0053_workout_performance_records_and_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutprogramexercise",
            name="performance_modes",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="نحوه ثبت عملکرد حرکت‌ها",
            ),
        ),
    ]
