# Generated by Django 4.2.15 on 2026-09-06 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_exercise_corrective_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه (تومان)'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='requires_payment',
            field=models.BooleanField(default=False, verbose_name='نیازمند پرداخت'),
        ),
        migrations.CreateModel(
            name='ClientDocumentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('initiated', 'پرداخت آغاز شده'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=16)),
                ('authority', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='account.clientdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
