# Generated by Django 4.2.15 on 2026-09-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_unique_active_access_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocumentpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت فایل', 'verbose_name_plural': 'پرداخت\u200cهای فایل'},
        ),
    ]
