HOME_FEATURED_COURSE_LIMIT = 6
HOME_LATEST_BLOG_LIMIT = 6
HOME_CATEGORY_LIMIT = 12
HOME_RELATED_ARTICLE_LIMIT = 3
HOME_SEARCH_LIMIT = 18
HOME_SERIES_FILTER_LIMIT = 0

HOME_SERIES_ENGAGEMENT_CACHE_PREFIX = "home:series:engagement"
HOME_SERIES_ENGAGEMENT_CACHE_TIMEOUT = 60 * 10

HOME_GLOBAL_BLOG_CACHE_PREFIX = "home:global_blogs"
HOME_GLOBAL_BLOG_CACHE_TIMEOUT = 60 * 10

HOME_PAGE_CACHE_PREFIX = "home:page"
HOME_PAGE_CACHE_TIMEOUT = 60 * 5

HOME_SEARCH_MAX_LENGTH = 255
