OTP_EXPIRATION_MINUTES = 5
OTP_CODE_LENGTH = 5
OTP_REQUEST_COOLDOWN_SECONDS = 120

SMS_BROADCAST_CHUNK_SIZE = 100
SMS_DEFAULT_TEMPLATE = "randcode"
GHASEDAK_OTP_PARAM = "param1"
SMS_REQUEST_TIMEOUT_SECONDS = 25
WHATSAPP_REQUEST_TIMEOUT_SECONDS = 25
WHATSAPP_API_VERSION = "v21.0"
WHATSAPP_UNAVAILABLE_ERROR_CODES = frozenset({131026, 131048, 131056})

SESSION_PHONE_CHANGE_TOKEN_KEY = "pending_phone_change_token"
SESSION_PHONE_CHANGE_VALUE_KEY = "pending_phone_change"
SESSION_PASSWORD_RESET_TOKEN_KEY = "password_reset_token"

GLOBAL_NOTIFICATION_CACHE_KEY = "account:global_notifications"
GLOBAL_NOTIFICATION_CACHE_TIMEOUT = 60 * 10

