from django.urls import path
from . import views
from . import admin_portal_views
from . import admin_portal_gym_views
from django.contrib.auth import views as auth_views

app_name = 'register'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('check_otp/', views.CheckOtpView.as_view(), name='verification'),
    path('resend_otp/', views.ResendOtpView.as_view(), name='resend_otp'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/analysis/', views.ProfileAnalysisView.as_view(), name='profile_analysis'),
    path('profile_courses/', views.ProfileCoursesView.as_view(), name='profile_course'),
    path('profile_plans/', views.ProfileDocumentsView.as_view(), name='profile_plans'),
    path('profile_plans/<int:pk>/pay/', views.ClientDocumentPaymentView.as_view(), name='profile_document_pay'),
    path('profile_plans/payment/verify/', views.ClientDocumentPaymentVerifyView.as_view(), name='profile_document_verify'),
    path('profile_plans/<int:pk>/download/', views.ClientDocumentDownloadView.as_view(), name='profile_document_download'),
    path('profile/workout-programs/', views.ProfileWorkoutProgramsView.as_view(), name='profile_workout_programs'),
    path('profile/workout-programs/<int:pk>/performance/', views.ProfileWorkoutProgramPerformanceView.as_view(), name='profile_workout_program_performance'),
    path('profile/workout-programs/<int:pk>/pay/', views.WorkoutProgramPaymentView.as_view(), name='profile_workout_program_pay'),
    path('profile/workout-programs/payment/verify/', views.WorkoutProgramPaymentVerifyView.as_view(), name='profile_workout_program_verify'),
    path('profile/workout-programs/<int:pk>/pdf/', views.ProfileWorkoutProgramPdfView.as_view(), name='profile_workout_program_pdf'),
    path('profile/workout-programs/movement/<slug:kind>/<int:movement_id>/', views.ProfileWorkoutMovementView.as_view(), name='profile_workout_movement'),
    path('profile/coach/', views.ProfileCoachView.as_view(), name='profile_coach'),
    path('profile_financial/', views.ProfileFinancialView.as_view(), name='profile_financial'),
    path('profile_comments/', views.ProfileCommentsView.as_view(), name='profile_comments'),
    path('profile_notifications/', views.ProfileNotificationsView.as_view(), name='profile_notifications'),
    path('profile_useredit/', views.edit_user_profile, name='profile_useredit'),
    path('profile_number_edit/', views.NumberEdit.as_view(), name='profile_number_edit'),
    path('profile_number_verify/', views.NumberEditVerify.as_view(), name='profile_number_verify'),
    path('profile/metric/<slug:metric>/', views.ProfileMetricEditView.as_view(), name='profile_metric_edit'),
    path('profile/weight/', views.ProfileMetricEditView.as_view(), {'metric': 'weight'}, name='profile_weight_edit'),
    path('profile/height/', views.ProfileMetricEditView.as_view(), {'metric': 'height'}, name='profile_height_edit'),
    path('profile/birth-date/', views.ProfileMetricEditView.as_view(), {'metric': 'birth_date'}, name='profile_birth_date_edit'),
    path('profile/blood-group/', views.ProfileMetricEditView.as_view(), {'metric': 'blood_group'}, name='profile_blood_group_edit'),
    path('pass_register/', views.signup, name='pass_register'),
    path('pass_login/', views.login_view, name='pass_login'),
    path('forgot_password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('forgot_password/confirm/', views.ForgotPasswordConfirmView.as_view(), name='forgot_password_confirm'),
    path('password_change/', views.PasswordsChangeView.as_view(), name='change_password'),
    path('add_course/<int:series_id>/', views.AddCourseToProfileView.as_view(), name='add_course_to_profile'),
    path('admin/', admin_portal_views.AdminSearchView.as_view(), name='admin_search'),
    path('admin/users/<int:user_id>/', admin_portal_views.AdminUserHubView.as_view(), name='admin_user_hub'),
    path('admin/users/<int:user_id>/personal/', admin_portal_views.AdminPersonalInfoView.as_view(), name='admin_personal_info'),
    path('admin/users/<int:user_id>/circumference/', admin_portal_views.AdminCircumferenceView.as_view(), name='admin_circumference'),
    path('admin/users/<int:user_id>/circumference/<int:pk>/edit/', admin_portal_views.AdminCircumferenceEditView.as_view(), name='admin_circumference_edit'),
    path('admin/users/<int:user_id>/caliper/', admin_portal_views.AdminCaliperView.as_view(), name='admin_caliper'),
    path('admin/users/<int:user_id>/caliper/<int:pk>/edit/', admin_portal_views.AdminCaliperEditView.as_view(), name='admin_caliper_edit'),
    path('admin/users/<int:user_id>/measurements/', admin_portal_views.AdminMeasurementHistoryView.as_view(), name='admin_measurement_history'),
    path('admin/users/<int:user_id>/analysis/', admin_portal_views.AdminUserAnalysisView.as_view(), name='admin_user_analysis'),
    path('admin/users/<int:user_id>/upload/', admin_portal_views.AdminUploadView.as_view(), name='admin_upload'),
    path('admin/users/<int:user_id>/role/', admin_portal_views.AdminRoleToggleView.as_view(), name='admin_role_toggle'),
    path('admin/coach-requests/<int:pk>/handled/', admin_portal_views.CoachRequestMarkHandledView.as_view(), name='admin_coach_request_handled'),
    path('admin/coach-requests/<int:pk>/push-measurements/', admin_portal_views.CoachRequestPushMeasurementsView.as_view(), name='admin_coach_request_push'),
    path('admin/notifications/', admin_portal_views.AdminNotificationsView.as_view(), name='admin_notifications'),
    path('admin/notifications/moderate/', admin_portal_views.AdminCommentModerationView.as_view(), name='admin_comment_moderate'),

    path('admin/library/', admin_portal_gym_views.GymLibraryView.as_view(), name='admin_gym_library'),
    path('admin/automatic-programming/', admin_portal_gym_views.AutomaticProgrammingView.as_view(), name='admin_automatic_programming'),
    path('admin/users/<int:user_id>/programs/', admin_portal_gym_views.AdminProgramListView.as_view(), name='admin_program_list'),
    path('admin/users/<int:user_id>/programs/add/', admin_portal_gym_views.AdminProgramFormView.as_view(), name='admin_program_add'),
    path('admin/users/<int:user_id>/programs/<int:pk>/edit/', admin_portal_gym_views.AdminProgramFormView.as_view(), name='admin_program_edit'),
    path('admin/users/<int:user_id>/programs/<int:pk>/delete/', admin_portal_gym_views.AdminProgramDeleteView.as_view(), name='admin_program_delete'),
    path('admin/users/<int:user_id>/programs/<int:pk>/pdf/', admin_portal_gym_views.AdminProgramPdfView.as_view(), name='admin_program_pdf'),
    path('admin/library/muscles/', admin_portal_gym_views.MuscleListView.as_view(), name='admin_muscle_list'),
    path('admin/library/muscles/add/', admin_portal_gym_views.MuscleFormView.as_view(), name='admin_muscle_add'),
    path('admin/library/muscles/<int:pk>/edit/', admin_portal_gym_views.MuscleFormView.as_view(), name='admin_muscle_edit'),
    path('admin/library/muscles/<int:pk>/delete/', admin_portal_gym_views.MuscleDeleteView.as_view(), name='admin_muscle_delete'),
    path('admin/library/exercises/', admin_portal_gym_views.ExerciseListView.as_view(), name='admin_exercise_list'),
    path('admin/library/exercises/add/', admin_portal_gym_views.ExerciseFormView.as_view(), name='admin_exercise_add'),
    path('admin/library/exercises/<int:pk>/edit/', admin_portal_gym_views.ExerciseFormView.as_view(), name='admin_exercise_edit'),
    path('admin/library/exercises/<int:pk>/delete/', admin_portal_gym_views.ExerciseDeleteView.as_view(), name='admin_exercise_delete'),

    path('admin/library/correctives/', admin_portal_gym_views.CorrectiveExerciseListView.as_view(), name='admin_corrective_list'),
    path('admin/library/correctives/add/', admin_portal_gym_views.CorrectiveExerciseFormView.as_view(), name='admin_corrective_add'),
    path('admin/library/correctives/<int:pk>/edit/', admin_portal_gym_views.CorrectiveExerciseFormView.as_view(), name='admin_corrective_edit'),
    path('admin/library/correctives/<int:pk>/delete/', admin_portal_gym_views.CorrectiveExerciseDeleteView.as_view(), name='admin_corrective_delete'),

    path('admin/library/lookup/<slug:key>/', admin_portal_gym_views.LookupListView.as_view(), name='admin_lookup_list'),
    path('admin/library/lookup/<slug:key>/add/', admin_portal_gym_views.LookupFormView.as_view(), name='admin_lookup_add'),
    path('admin/library/lookup/<slug:key>/<int:pk>/edit/', admin_portal_gym_views.LookupFormView.as_view(), name='admin_lookup_edit'),
    path('admin/library/lookup/<slug:key>/<int:pk>/delete/', admin_portal_gym_views.LookupDeleteView.as_view(), name='admin_lookup_delete'),

    path('admin/coaches/', admin_portal_views.AdminCoachManagementView.as_view(), name='admin_coach_management'),
    path('admin/password-change/', admin_portal_views.AdminPasswordChangeView.as_view(), name='admin_password_change'),
    path('admin/clients/', admin_portal_views.AdminUserListView.as_view(), name='admin_user_list'),
    path('admin/clients/add/', admin_portal_views.AdminUserCreateView.as_view(), name='admin_user_add'),
    path('admin/clients/<int:user_id>/delete/', admin_portal_views.AdminUserDeleteView.as_view(), name='admin_user_delete'),
]
