# Generated by Django 4.2.15 on 2024-08-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_alter_seriesmodel_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
