# Generated by Django 4.2.15 on 2024-08-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_advantage_seriesmodel_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='icon',
        ),
    ]
