# Generated by Django 4.2.15 on 2024-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_remove_advantage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblogmodel',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
