# Generated by Django 4.2.15 on 2024-08-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_articleblogmodel_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblogmodel',
            name='author_image',
        ),
        migrations.AlterField(
            model_name='articleblogmodel',
            name='language_kinds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='home.category', verbose_name='زبان'),
        ),
    ]
