# Generated by Django 6.0.5 on 2026-05-10 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_articleblogmodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number', 'id'], 'verbose_name': 'اپیزود', 'verbose_name_plural': 'اپیزودها'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['number', 'id'], 'verbose_name': 'فصل', 'verbose_name_plural': 'فصل ها'},
        ),
        migrations.AddField(
            model_name='episode',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'episode_number'], name='home_episod_season__8c314a_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user', 'series'], name='home_userco_user_id_d4f4da_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['series', 'added_at'], name='home_userco_series__08483a_idx'),
        ),
    ]
