# Generated by Django 6.0.5 on 2026-05-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_alter_episode_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
