# Generated by Django 6.0.5 on 2026-05-12 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_alter_comment_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='is_compeleted',
            field=models.BooleanField(db_index=True, default=True, verbose_name='تکمیل شده'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='عنوان'),
        ),
        migrations.AddIndex(
            model_name='articleblogmodel',
            index=models.Index(fields=['author', 'id'], name='home_articl_author__3e01c6_idx'),
        ),
        migrations.AddIndex(
            model_name='articleblogmodel',
            index=models.Index(fields=['language_kinds', 'id'], name='home_articl_languag_a48dde_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='home_catego_slug_86c5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='commentsectionmodel',
            index=models.Index(fields=['series', 'created_at'], name='home_commen_series__4353ad_idx'),
        ),
        migrations.AddIndex(
            model_name='commentsectionmodel',
            index=models.Index(fields=['user', 'created_at'], name='home_commen_user_id_c07788_idx'),
        ),
        migrations.AddIndex(
            model_name='commentsectionmodel',
            index=models.Index(fields=['is_active', 'created_at'], name='home_commen_is_acti_eb65e4_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['comment', 'created_at'], name='home_reply_comment_608172_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['user', 'created_at'], name='home_reply_user_id_a7f151_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['is_active', 'created_at'], name='home_reply_is_acti_955154_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['series', 'number'], name='home_season_series__9066b1_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesmodel',
            index=models.Index(fields=['author', 'id'], name='home_series_author__e72034_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesmodel',
            index=models.Index(fields=['language_kinds', 'id'], name='home_series_languag_ba9a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesmodel',
            index=models.Index(fields=['free', 'id'], name='home_series_free_8fe3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesmodel',
            index=models.Index(fields=['is_compeleted', 'id'], name='home_series_is_comp_4b94c7_idx'),
        ),
    ]
