# Generated by Django 6.0.5 on 2026-05-26 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_alter_seriesmodel_is_compeleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='home', editable=False, unique=True)),
                ('title', models.CharField(default='صفحه اصلی', max_length=120, verbose_name='عنوان صفحه')),
                ('hero_eyebrow', models.CharField(default='آموزش حرفه\u200cای و ساختارمند', max_length=120, verbose_name='متن بالای هدر')),
                ('hero_title', models.CharField(default='مسیر یادگیری حرفه\u200cای، سریع و ساختارمند', max_length=255, verbose_name='عنوان هدر')),
                ('hero_description', models.TextField(default='دوره\u200cها، مقالات و مسیرهای آموزشی با تجربه کاربری مدرن و دسترسی سریع\u200cتر آماده شده\u200cاند.', verbose_name='توضیحات هدر')),
                ('hero_primary_label', models.CharField(default='شروع یادگیری', max_length=80, verbose_name='متن دکمه اصلی')),
                ('hero_primary_url', models.CharField(default='/series/', max_length=255, verbose_name='لینک دکمه اصلی')),
                ('hero_secondary_label', models.CharField(default='مشاوره', max_length=80, verbose_name='متن دکمه دوم')),
                ('hero_secondary_url', models.CharField(default='/contact_us/', max_length=255, verbose_name='لینک دکمه دوم')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home_images', verbose_name='تصویر هدر')),
                ('hero_image_alt', models.CharField(default='تصویر اصلی صفحه', max_length=255, verbose_name='متن جایگزین تصویر')),
                ('stats_eyebrow', models.CharField(default='سیستم یادگیری', max_length=120, verbose_name='متن بخش آمار')),
                ('stats_title', models.CharField(default='تجربه یکپارچه آموزش', max_length=200, verbose_name='عنوان بخش آمار')),
                ('stats_description', models.TextField(default='دسترسی سریع به دوره\u200cها، مقالات و مسیرهای پیشنهادی با ساختار شفاف\u200cتر.', verbose_name='توضیحات بخش آمار')),
                ('stat_total_courses_label', models.CharField(default='دوره فعال', max_length=120, verbose_name='برچسب دوره فعال')),
                ('stat_free_courses_label', models.CharField(default='دوره رایگان', max_length=120, verbose_name='برچسب دوره رایگان')),
                ('stat_completed_courses_label', models.CharField(default='دوره تکمیل\u200cشده', max_length=120, verbose_name='برچسب دوره تکمیل\u200cشده')),
                ('stat_articles_label', models.CharField(default='محتوای آموزشی', max_length=120, verbose_name='برچسب مقالات')),
                ('featured_courses_eyebrow', models.CharField(default='دوره\u200cهای منتخب', max_length=120, verbose_name='متن بخش دوره\u200cها')),
                ('featured_courses_title', models.CharField(default='آخرین دوره\u200cهای منتشر شده', max_length=200, verbose_name='عنوان بخش دوره\u200cها')),
                ('featured_courses_description', models.TextField(default='منتخب دوره\u200cها با ارائه\u200cای شفاف\u200cتر، کارت\u200cهای مدرن\u200cتر و دسترسی سریع\u200cتر به جزئیات.', verbose_name='توضیحات بخش دوره\u200cها')),
                ('featured_courses_button_label', models.CharField(default='مشاهده همه', max_length=80, verbose_name='متن دکمه بخش دوره\u200cها')),
                ('featured_courses_button_url', models.CharField(default='/series/', max_length=255, verbose_name='لینک دکمه بخش دوره\u200cها')),
                ('article_eyebrow', models.CharField(default='محتوای آموزشی', max_length=120, verbose_name='متن بخش وبلاگ')),
                ('article_title', models.CharField(default='آخرین نوشته\u200cهای آموزشی', max_length=200, verbose_name='عنوان بخش وبلاگ')),
                ('article_description', models.TextField(default='مطالب آموزشی با چیدمان خواناتر و تجربه مطالعه بهتر.', verbose_name='توضیحات بخش وبلاگ')),
                ('article_button_label', models.CharField(default='آرشیو مقالات', max_length=80, verbose_name='متن دکمه بخش وبلاگ')),
                ('article_button_url', models.CharField(default='/blog/', max_length=255, verbose_name='لینک دکمه بخش وبلاگ')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='HomePageFeaturePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('icon', models.CharField(choices=[('book', 'کتاب'), ('shield', 'امنیت'), ('lightning', 'سرعت'), ('support', 'پشتیبانی')], default='book', max_length=20, verbose_name='آیکن')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_points', to='home.homepage', verbose_name='صفحه اصلی')),
            ],
            options={
                'verbose_name': 'نکته کلیدی',
                'verbose_name_plural': 'نکات کلیدی',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('home_page', 'sort_order'), name='unique_home_page_feature_order')],
            },
        ),
        migrations.CreateModel(
            name='HomePageHighlightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('top', 'بالا'), ('bottom', 'پایین')], max_length=20, verbose_name='موقعیت')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_cards', to='home.homepage', verbose_name='صفحه اصلی')),
            ],
            options={
                'verbose_name': 'کارت شناور',
                'verbose_name_plural': 'کارت\u200cهای شناور',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('home_page', 'position'), name='unique_home_page_highlight_position')],
            },
        ),
        migrations.CreateModel(
            name='HomePageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='توضیحات')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='home.homepage', verbose_name='صفحه اصلی')),
            ],
            options={
                'verbose_name': 'شاخص هدر',
                'verbose_name_plural': 'شاخص\u200cهای هدر',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('home_page', 'sort_order'), name='unique_home_page_metric_order')],
            },
        ),
        migrations.CreateModel(
            name='HomePageTrustItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_items', to='home.homepage', verbose_name='صفحه اصلی')),
            ],
            options={
                'verbose_name': 'نشان اعتماد',
                'verbose_name_plural': 'نشان\u200cهای اعتماد',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('home_page', 'sort_order'), name='unique_home_page_trust_order')],
            },
        ),
    ]
