# Generated by Django 6.0.5 on 2026-05-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_homepage_homepagefeaturepoint_homepagehighlightcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='article_button_label',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه بخش وبلاگ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='article_button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک دکمه بخش وبلاگ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='article_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش وبلاگ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='article_eyebrow',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش وبلاگ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='article_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش وبلاگ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_courses_button_label',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه بخش دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_courses_button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک دکمه بخش دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_courses_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_courses_eyebrow',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_courses_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_primary_label',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه اصلی'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_primary_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک دکمه اصلی'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_secondary_label',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه دوم'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_secondary_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک دکمه دوم'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_articles_label',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب مقالات'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_completed_courses_label',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره تکمیل\u200cشده'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_free_courses_label',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره رایگان'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stat_total_courses_label',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره فعال'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stats_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش آمار'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stats_eyebrow',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش آمار'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stats_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش آمار'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان صفحه'),
        ),
    ]
