# Generated by Django 4.2.15 on 2026-06-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_update_hero_secondary_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogListingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='blog-listing', editable=False, unique=True)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر')),
                ('hero_description', models.TextField(blank=True, null=True, verbose_name='توضیحات هدر')),
            ],
            options={
                'verbose_name': 'صفحه آرشیو بلاگ',
                'verbose_name_plural': 'صفحه آرشیو بلاگ',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='contact', editable=False, unique=True)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر')),
                ('hero_description', models.TextField(blank=True, null=True, verbose_name='توضیحات هدر')),
                ('status_title', models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان کادر وضعیت')),
                ('status_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کادر وضعیت')),
            ],
            options={
                'verbose_name': 'صفحه تماس با ما',
                'verbose_name_plural': 'صفحه تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='عنوان')),
                ('url', models.CharField(max_length=255, verbose_name='لینک')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'لینک ناوبری',
                'verbose_name_plural': 'لینک\u200cهای ناوبری',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeriesListingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='series-listing', editable=False, unique=True)),
                ('hero_eyebrow', models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر')),
                ('hero_description', models.TextField(blank=True, null=True, verbose_name='توضیحات هدر')),
            ],
            options={
                'verbose_name': 'صفحه آرشیو دوره\u200cها',
                'verbose_name_plural': 'صفحه آرشیو دوره\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='default', editable=False, unique=True)),
                ('brand_eyebrow', models.CharField(blank=True, max_length=60, null=True, verbose_name='متن کوچک برند')),
                ('brand_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='نام برند')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار سایت')),
                ('header_search_placeholder', models.CharField(blank=True, max_length=120, null=True, verbose_name='متن جای\u200cخالی جستجو')),
                ('default_meta_title', models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان پیش\u200cفرض صفحات')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.AddField(
            model_name='footer',
            name='about_eyebrow',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای بخش درباره'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بخش درباره'),
        ),
        migrations.AddField(
            model_name='footer',
            name='links_section_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان بخش لینک\u200cهای مفید'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_section_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان بخش شبکه\u200cهای اجتماعی'),
        ),
        migrations.AddField(
            model_name='footer',
            name='trust_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن نماد اعتماد'),
        ),
        migrations.CreateModel(
            name='SeriesListingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160, verbose_name='متن')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('series_listing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='home.serieslistingpage', verbose_name='صفحه آرشیو')),
            ],
            options={
                'verbose_name': 'نکته آرشیو دوره\u200cها',
                'verbose_name_plural': 'نکات آرشیو دوره\u200cها',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120, verbose_name='متن')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش')),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='home.contactpage', verbose_name='صفحه تماس')),
            ],
            options={
                'verbose_name': 'نکته صفحه تماس',
                'verbose_name_plural': 'نکات صفحه تماس',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
