# Generated by Django 4.2.15 on 2026-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_seed_navigation_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='hero_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='hero_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='hero_eyebrow_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AddField(
            model_name='bloglistingpage',
            name='hero_title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, help_text='عنوان دسته بندی را وارد کنید', max_length=100, null=True, verbose_name='عنوان دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_fa',
            field=models.CharField(blank=True, help_text='عنوان دسته بندی را وارد کنید', max_length=100, null=True, verbose_name='عنوان دسته بندی'),
        ),
        migrations.AddField(
            model_name='categoryblog',
            name='title_en',
            field=models.CharField(blank=True, help_text='عنوان دسته بندی را وارد کنید', max_length=100, null=True, verbose_name='عنوان دسته بندی'),
        ),
        migrations.AddField(
            model_name='categoryblog',
            name='title_fa',
            field=models.CharField(blank=True, help_text='عنوان دسته بندی را وارد کنید', max_length=100, null=True, verbose_name='عنوان دسته بندی'),
        ),
        migrations.AddField(
            model_name='community',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_eyebrow_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='status_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کادر وضعیت'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='status_description_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیح کادر وضعیت'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='status_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان کادر وضعیت'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='status_title_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان کادر وضعیت'),
        ),
        migrations.AddField(
            model_name='contactpagesignal',
            name='text_en',
            field=models.CharField(max_length=120, null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='contactpagesignal',
            name='text_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='counseling',
            name='button_content_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='button_content_fa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='subtitle_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counseling',
            name='title_fa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='downcontent',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='downcontent',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='downcontent',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='downcontent',
            name='title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای بخش درباره'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_eyebrow_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای بخش درباره'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بخش درباره'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بخش درباره'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_us_en',
            field=models.TextField(null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_us_fa',
            field=models.TextField(null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='footer',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='footer',
            name='address_fa',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='footer',
            name='links_section_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان بخش لینک\u200cهای مفید'),
        ),
        migrations.AddField(
            model_name='footer',
            name='links_section_title_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان بخش لینک\u200cهای مفید'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_section_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان بخش شبکه\u200cهای اجتماعی'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_section_title_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان بخش شبکه\u200cهای اجتماعی'),
        ),
        migrations.AddField(
            model_name='footer',
            name='trust_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='متن نماد اعتماد'),
        ),
        migrations.AddField(
            model_name='footer',
            name='trust_text_fa',
            field=models.TextField(blank=True, null=True, verbose_name='متن نماد اعتماد'),
        ),
        migrations.AddField(
            model_name='footer',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ساعات کاری'),
        ),
        migrations.AddField(
            model_name='footer',
            name='working_hours_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ساعات کاری'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_button_label_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_button_label_fa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_eyebrow_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='article_title_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش وبلاگ'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_courses_button_label_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه بخش دوره\u200cها'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_courses_button_label_fa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه بخش دوره\u200cها'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_courses_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش دوره\u200cها'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_courses_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش دوره\u200cها'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_courses_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش دوره\u200cها'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_courses_eyebrow_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش دوره\u200cها'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_courses_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش دوره\u200cها'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_courses_title_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش دوره\u200cها'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_alt_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_label_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه اصلی'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_label_fa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه اصلی'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_label_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه دوم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_label_fa',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='متن دکمه دوم'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_articles_label_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب مقالات'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_articles_label_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب مقالات'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_completed_courses_label_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره تکمیل\u200cشده'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_completed_courses_label_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره تکمیل\u200cشده'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_free_courses_label_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره رایگان'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_free_courses_label_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره رایگان'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_total_courses_label_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره فعال'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat_total_courses_label_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='برچسب دوره فعال'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش آمار'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بخش آمار'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش آمار'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_eyebrow_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بخش آمار'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش آمار'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_title_fa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان بخش آمار'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان صفحه'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان صفحه'),
        ),
        migrations.AddField(
            model_name='homepagefeaturepoint',
            name='title_en',
            field=models.CharField(max_length=160, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepagefeaturepoint',
            name='title_fa',
            field=models.CharField(max_length=160, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepagehighlightcard',
            name='description_en',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='homepagehighlightcard',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='homepagehighlightcard',
            name='title_en',
            field=models.CharField(max_length=160, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepagehighlightcard',
            name='title_fa',
            field=models.CharField(max_length=160, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepagemetric',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='homepagemetric',
            name='description_fa',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='homepagemetric',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepagemetric',
            name='title_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepagemetric',
            name='value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='مقدار'),
        ),
        migrations.AddField(
            model_name='homepagemetric',
            name='value_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='مقدار'),
        ),
        migrations.AddField(
            model_name='homepagetrustitem',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='homepagetrustitem',
            name='title_fa',
            field=models.CharField(max_length=120, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='label_en',
            field=models.CharField(max_length=60, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='label_fa',
            field=models.CharField(max_length=60, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='serieslistingpage',
            name='hero_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AddField(
            model_name='serieslistingpage',
            name='hero_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات هدر'),
        ),
        migrations.AddField(
            model_name='serieslistingpage',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AddField(
            model_name='serieslistingpage',
            name='hero_eyebrow_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن بالای هدر'),
        ),
        migrations.AddField(
            model_name='serieslistingpage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AddField(
            model_name='serieslistingpage',
            name='hero_title_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان هدر'),
        ),
        migrations.AddField(
            model_name='serieslistingsignal',
            name='text_en',
            field=models.CharField(max_length=160, null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='serieslistingsignal',
            name='text_fa',
            field=models.CharField(max_length=160, null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_eyebrow_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='متن کوچک برند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_eyebrow_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='متن کوچک برند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='نام برند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='نام برند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان پیش\u200cفرض صفحات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_title_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان پیش\u200cفرض صفحات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_search_placeholder_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن جای\u200cخالی جستجو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_search_placeholder_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='متن جای\u200cخالی جستجو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شعار سایت'),
        ),
    ]
