# Generated by Django 4.2.15 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0106_aboutpage_description_en_aboutpage_description_fa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleBlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="articles_blog/gallery", verbose_name="تصویر")),
                ("alt_text", models.CharField(blank=True, max_length=255, verbose_name="متن جایگزین")),
                ("caption", models.CharField(blank=True, max_length=255, verbose_name="عنوان تصویر")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="home.articleblogmodel",
                        verbose_name="مقاله",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر مقاله",
                "verbose_name_plural": "تصاویر مقاله",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ArticleBlogLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="متن لینک")),
                ("url", models.CharField(max_length=500, verbose_name="آدرس لینک")),
                (
                    "open_in_new_tab",
                    models.BooleanField(default=True, verbose_name="باز شدن در زبانه جدید"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_links",
                        to="home.articleblogmodel",
                        verbose_name="مقاله",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک مقاله",
                "verbose_name_plural": "لینک‌های مقاله",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
