# Generated by Django 4.2.15 on 2026-09-06 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0107_articleblogimage_articlebloglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_response',
            field=models.TextField(blank=True, verbose_name='پاسخ مدیر'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='منتشر شود'),
        ),
        migrations.AddField(
            model_name='comment',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
