# Generated by Django 4.2.15 on 2026-09-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_comment_admin_response_comment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication_status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='commentsectionmodel',
            name='publication_status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=16),
        ),
    ]
