"""
Django settings for sport_shop project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import sys
from pathlib import Path
from typing import List
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load the conventional ``.env`` file first.  This repository historically
# shipped its local development variables in a file named ``env`` (without
# the leading dot), so use that as a backwards-compatible fallback for any
# values that are not already set. An empty ``.env`` file should not hide the
# legacy file.
load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR / "env")






def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, "true" if default else "false").strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str) -> List[str]:
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


def env_path(name: str, default: str) -> str:
    raw = os.getenv(name, "").strip()
    if not raw:
        return default
    if os.name != "nt" and len(raw) >= 2 and raw[1] == ":":
        return default
    return raw


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG or env_bool("DJANGO_ALLOW_INSECURE_DEV_SECRET", default=False):
        SECRET_KEY = "django-insecure-dev-only-change-me"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.")

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "egofit.ir,www.egofit.ir,127.0.0.1,localhost")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "https://egofit.ir,https://www.egofit.ir")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_REFERRER_POLICY = "same-origin"
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "31536000"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=not DEBUG)

# Production must not be able to accidentally disable transport protections via
# a stale or incomplete environment file.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = max(SECURE_HSTS_SECONDS, 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# The project currently contains inline scripts/styles, so the policy keeps
# those temporarily compatible while still restricting origins, framing,
# plugins, form targets and resource types. Refactor inline code to nonces or
# hashes as a follow-up for a stricter script-src policy.
CONTENT_SECURITY_POLICY = os.getenv(
    "DJANGO_CONTENT_SECURITY_POLICY",
    "default-src 'self'; "
    "base-uri 'self'; "
    "object-src 'none'; "
    "frame-ancestors 'none'; "
    "form-action 'self' https:; "
    "img-src 'self' data: blob: https:; "
    "media-src 'self' blob: https:; "
    "font-src 'self' data: https:; "
    "style-src 'self' 'unsafe-inline' https:; "
    "script-src 'self' 'unsafe-inline' https:; "
    "connect-src 'self' https:; "
    "frame-src 'self' https://www.youtube.com https://player.vimeo.com",
).strip()
CONTENT_SECURITY_POLICY_REPORT_ONLY = env_bool(
    "DJANGO_CSP_REPORT_ONLY", default=False
)
# Application definition

INSTALLED_APPS = [
    "admin_persian",
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'home.apps.HomeConfig',
    'account.apps.AccountConfig',
    'cart.apps.CartConfig',
    'api.apps.ApiConfig',
    'dbbackup',
    'storages',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'sport_shop.security_headers.SecurityHeadersMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'sport_shop.middleware.ResilientSessionMiddleware',
    'sport_shop.middleware.ForceDefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.cors.ApiCorsMiddleware',
    'api.middleware.ApiBearerAuthenticationMiddleware',
    'cart.cart_middleware.CartMiddleware',
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default
    # Your custom backend, if any
]
ROOT_URLCONF = 'sport_shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'context_processors.context_processors.categories',
                'context_processors.context_processors.footer_context_processor',
                'context_processors.context_processors.blogs_processor',
                'context_processors.context_processors.site_settings',
                'context_processors.context_processors.navigation_links',

            ],
        },
    },
]

WSGI_APPLICATION = 'sport_shop.wsgi.application'

# Database#
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

if env_bool("DJANGO_USE_SQLITE", default=True):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    db_name = os.getenv("DJANGO_DB_NAME", "egofitir_EgoFit_App")
    db_user = os.getenv("DJANGO_DB_USER", "")
    db_password = os.getenv("DJANGO_DB_PASSWORD", "")
    db_host = os.getenv("DJANGO_DB_HOST", "localhost")
    db_port = os.getenv("DJANGO_DB_PORT", "3306")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
        }
    }

# 

if DATABASES["default"]["ENGINE"].endswith("sqlite3"):
    SILENCED_SYSTEM_CHECKS = ["fields.E180"]

REDIS_URL = os.getenv("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 300,
            "KEY_PREFIX": "sport_shop",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "egofit-local-cache",
            "TIMEOUT": 300,
            "KEY_PREFIX": "sport_shop",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "Asia/Tehran")

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("fa", "فارسی"),
    ("en", "English"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]

MODELTRANSLATION_DEFAULT_LANGUAGE = "fa"
MODELTRANSLATION_LANGUAGES = ("fa", "en")
# Asymmetric on purpose: an empty English field falls back to Persian (so English
# visitors see something instead of blank text before a superadmin translates it),
# but Persian never falls back to English — a blank Persian field must fall through
# to the template-side `default_cms` filter, not silently surface English content.
MODELTRANSLATION_FALLBACK_LANGUAGES = {"default": (), "en": ("fa",)}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

STATIC_ROOT = env_path("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles"))
MEDIA_ROOT = env_path("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media"))


LIARA_PUBLIC_BASE_URL = os.getenv("LIARA_PUBLIC_BASE_URL", "").rstrip("/")
MEDIA_CACHE_MAX_AGE = int(os.getenv("MEDIA_CACHE_MAX_AGE", "86400"))
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_MAX_AGE = int(os.getenv("DJANGO_STATIC_MAX_AGE", "31536000" if not DEBUG else "0"))
DJANGO_AUTO_COLLECTSTATIC_ON_STARTUP = env_bool("DJANGO_AUTO_COLLECTSTATIC_ON_STARTUP", default=False)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "account.User"
LOGIN_URL = "/accounts/register/"

MERCHANT = os.getenv("ZARINPAL_MERCHANT_ID", "")
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SANDBOX = env_bool("ZARINPAL_SANDBOX", default=False)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 2592000
SESSION_SAVE_EVERY_REQUEST = False





EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL')

# S3 Settings
LIARA_ENDPOINT = os.getenv("LIARA_ENDPOINT")
LIARA_BUCKET_NAME = os.getenv("LIARA_BUCKET_NAME", "egofit").strip()
LIARA_ACCESS_KEY  = os.getenv("LIARA_ACCESS_KEY")
LIARA_SECRET_KEY  = os.getenv("LIARA_SECRET_KEY")

# S3 Settings Based on AWS (optional)
AWS_ACCESS_KEY_ID= LIARA_ACCESS_KEY
AWS_SECRET_ACCESS_KEY= LIARA_SECRET_KEY
AWS_STORAGE_BUCKET_NAME = LIARA_BUCKET_NAME
AWS_S3_ENDPOINT_URL= LIARA_ENDPOINT
AWS_S3_REGION_NAME= 'us-east-1'
AWS_QUERYSTRING_AUTH = False

# Django-storages configuration
STORAGES = {
  "default": {
      "BACKEND": "sport_shop.storage_backends.ResilientMediaStorage",
  },
  "staticfiles": {
      "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
  },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "home": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_HOME_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "account": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_ACCOUNT_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "cart": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_CART_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "sport_shop": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_PROJECT_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

DJANGO_AUTO_MIGRATE_ON_STARTUP = env_bool("DJANGO_AUTO_MIGRATE_ON_STARTUP", default=False)

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL or "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_ALWAYS_EAGER = env_bool("DJANGO_TASKS_RUN_INLINE", default=False)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "300"))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "270"))
DJANGO_TASK_QUEUE_REQUIRED = env_bool("DJANGO_TASK_QUEUE_REQUIRED", default=not DEBUG)
FFPROBE_BINARY = os.getenv("FFPROBE_BINARY", "ffprobe")
MAX_UPLOAD_SIZE = int(os.getenv("DJANGO_MAX_UPLOAD_SIZE", str(100 * 1024 * 1024)))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024))
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024))
)


GHASEDAK_API_KEY = os.getenv("GHASEDAK_API_KEY", "")
GHASEDAK_LINE_NUMBER = os.getenv("GHASEDAK_LINE_NUMBER", "")
GHASEDAK_OTP_TEMPLATE = os.getenv("GHASEDAK_OTP_TEMPLATE", "randcode")
GHASEDAK_OTP_PARAM = os.getenv("GHASEDAK_OTP_PARAM", "param1")

WHATSAPP_ENABLED = env_bool("WHATSAPP_ENABLED", default=False)
WHATSAPP_TOKEN = os.getenv("WHATSAPP_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_API_VERSION = os.getenv("WHATSAPP_API_VERSION", "v21.0")
WHATSAPP_TEMPLATE_NAME = os.getenv("WHATSAPP_TEMPLATE_NAME", "")
WHATSAPP_TEMPLATE_LANGUAGE = os.getenv("WHATSAPP_TEMPLATE_LANGUAGE", "fa")
WHATSAPP_TEMPLATE_INCLUDE_BODY = env_bool("WHATSAPP_TEMPLATE_INCLUDE_BODY", default=True)

# API clients use short-lived access tokens and rotating refresh tokens. The
# API never authenticates from Django's browser session cookie.
API_ACCESS_TOKEN_TTL_MINUTES = int(os.getenv("API_ACCESS_TOKEN_TTL_MINUTES", "15"))
API_REFRESH_TOKEN_TTL_DAYS = int(os.getenv("API_REFRESH_TOKEN_TTL_DAYS", "30"))
API_CORS_ALLOWED_ORIGINS = env_list("API_CORS_ALLOWED_ORIGINS", "")
