"""
Django settings for sport_shop project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from typing import List
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()






def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, "true" if default else "false").strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str) -> List[str]:
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


def env_path(name: str, default: str) -> str:
    raw = os.getenv(name, "").strip()
    if not raw:
        return default
    if os.name != "nt" and len(raw) >= 2 and raw[1] == ":":
        return default
    return raw


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", 'django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "egofit.ir,www.egofit.ir,127.0.0.1,localhost")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "https://egofit.ir,https://www.egofit.ir")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_REFERRER_POLICY = "same-origin"
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "31536000"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=not DEBUG)
# Application definition

INSTALLED_APPS = [
    "admin_persian",
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'home.apps.HomeConfig',
    'account.apps.AccountConfig',
    'cart.apps.CartConfig',
    'dbbackup',
    'storages',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'sport_shop.middleware.ResilientSessionMiddleware',
    'sport_shop.middleware.ForceDefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cart.cart_middleware.CartMiddleware',
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default
    # Your custom backend, if any
]
ROOT_URLCONF = 'sport_shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'context_processors.context_processors.article_blog',
                # 'context_processors.context_processors.series_info',
                'context_processors.context_processors.categories',
                'context_processors.context_processors.footer_context_processor',
                'context_processors.context_processors.blogs_processor',
                'context_processors.context_processors.site_settings',
                'context_processors.context_processors.navigation_links',

            ],
        },
    },
]

WSGI_APPLICATION = 'sport_shop.wsgi.application'

# Database#
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

if env_bool("DJANGO_USE_SQLITE", default=True):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    db_name = os.getenv("DJANGO_DB_NAME", "egofitir_EgoFit_App")
    db_user = os.getenv("DJANGO_DB_USER", "")
    db_password = os.getenv("DJANGO_DB_PASSWORD", "")
    db_host = os.getenv("DJANGO_DB_HOST", "localhost")
    db_port = os.getenv("DJANGO_DB_PORT", "3306")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
        }
    }

# 

if DATABASES["default"]["ENGINE"].endswith("sqlite3"):
    SILENCED_SYSTEM_CHECKS = ["fields.E180"]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "egofit-local-cache",
        "TIMEOUT": 300,
        "KEY_PREFIX": "sport_shop",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "Asia/Tehran")

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("fa", "فارسی"),
    ("en", "English"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]

MODELTRANSLATION_DEFAULT_LANGUAGE = "fa"
MODELTRANSLATION_LANGUAGES = ("fa", "en")
# Asymmetric on purpose: an empty English field falls back to Persian (so English
# visitors see something instead of blank text before a superadmin translates it),
# but Persian never falls back to English — a blank Persian field must fall through
# to the template-side `default_cms` filter, not silently surface English content.
MODELTRANSLATION_FALLBACK_LANGUAGES = {"default": (), "en": ("fa",)}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets',
]

STATIC_ROOT = env_path("DJANGO_STATIC_ROOT", "/home/egofitir/public_html/static")
MEDIA_ROOT = env_path("DJANGO_MEDIA_ROOT", "/home/egofitir/public_html/media")


LIARA_PUBLIC_BASE_URL = os.getenv("LIARA_PUBLIC_BASE_URL", "https://egofit.ir").rstrip("/")
MEDIA_CACHE_MAX_AGE = int(os.getenv("MEDIA_CACHE_MAX_AGE", "86400"))
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_MAX_AGE = int(os.getenv("DJANGO_STATIC_MAX_AGE", "31536000" if not DEBUG else "0"))
DJANGO_AUTO_COLLECTSTATIC_ON_STARTUP = env_bool("DJANGO_AUTO_COLLECTSTATIC_ON_STARTUP", default=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "account.User"
LOGIN_URL = "/accounts/register/"

MERCHANT = os.getenv("ZARINPAL_MERCHANT_ID", "")
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SANDBOX = env_bool("ZARINPAL_SANDBOX", default=False)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 2592000
SESSION_SAVE_EVERY_REQUEST = False





EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL')

# S3 Settings
LIARA_ENDPOINT = os.getenv("LIARA_ENDPOINT")
LIARA_BUCKET_NAME = os.getenv("LIARA_BUCKET_NAME")
LIARA_ACCESS_KEY  = os.getenv("LIARA_ACCESS_KEY")
LIARA_SECRET_KEY  = os.getenv("LIARA_SECRET_KEY")

# S3 Settings Based on AWS (optional)
AWS_ACCESS_KEY_ID= LIARA_ACCESS_KEY
AWS_SECRET_ACCESS_KEY= LIARA_SECRET_KEY
AWS_STORAGE_BUCKET_NAME = LIARA_BUCKET_NAME
AWS_S3_ENDPOINT_URL= LIARA_ENDPOINT
AWS_S3_REGION_NAME= 'us-east-1'
AWS_QUERYSTRING_AUTH = False

# Django-storages configuration
STORAGES = {
  "default": {
      "BACKEND": "sport_shop.storage_backends.ResilientMediaStorage",
  },
  "staticfiles": {
      "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
  },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "home": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_HOME_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "account": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_ACCOUNT_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "cart": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_CART_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "sport_shop": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_PROJECT_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

DJANGO_AUTO_MIGRATE_ON_STARTUP = env_bool("DJANGO_AUTO_MIGRATE_ON_STARTUP", default=True)


GHASEDAK_API_KEY = os.getenv("GHASEDAK_API_KEY", "")
GHASEDAK_LINE_NUMBER = os.getenv("GHASEDAK_LINE_NUMBER", "")
GHASEDAK_OTP_TEMPLATE = os.getenv("GHASEDAK_OTP_TEMPLATE", "randcode")
GHASEDAK_OTP_PARAM = os.getenv("GHASEDAK_OTP_PARAM", "param1")
