# Generated by Django 6.0.5 on 2026-05-10 12:33

import django.db.models.deletion
from uuid import uuid4

from django.conf import settings
from django.db import migrations, models


def populate_order_checkout_fields(apps, schema_editor):
    Order = apps.get_model('cart', 'Order')
    for order in Order.objects.all().iterator():
        order.order_number = uuid4().hex[:16].upper()
        order.subtotal_price = order.total_price or 0
        order.discount_amount = 0
        order.status = 'paid' if order.is_paid else 'pending'
        order.save(update_fields=['order_number', 'subtotal_price', 'discount_amount', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_alter_order_options_order_course'),
        ('home', '0098_alter_episode_options_alter_season_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='order',
            name='applied_discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.discountcode'),
        ),
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_initiated', 'Payment Initiated'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_price',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ اولیه'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل'),
        ),
        migrations.RunPython(populate_order_checkout_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='cart_order_user_id_fd75e4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'is_paid'], name='cart_order_user_id_c95ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='cart_order_created_650373_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='cart_orderi_order_i_bd3545_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'order'], name='cart_orderi_product_e57d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='userdiscountcode',
            index=models.Index(fields=['user', 'discount_code'], name='cart_userdi_user_id_b8f227_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product'),
        ),
    ]
