# Generated by Django 4.2.15 on 2026-06-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_discountcode_is_active_order_applied_discount_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['is_active'], name='cart_discou_is_acti_7638f1_idx'),
        ),
    ]
