from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    path("health/", views.health, name="health"),
    path("auth/register/", views.register, name="register"),
    path("auth/login/", views.login, name="login"),
    path("auth/otp/request/", views.otp_request, name="otp_request"),
    path("auth/otp/verify/", views.otp_verify, name="otp_verify"),
    path("auth/password-reset/request/", views.password_reset_request, name="password_reset_request"),
    path("auth/password-reset/confirm/", views.password_reset_confirm, name="password_reset_confirm"),
    path("auth/refresh/", views.refresh, name="refresh"),
    path("auth/logout/", views.logout, name="logout"),
    path("me/", views.me, name="me"),
    path("me/password/change/", views.password_change, name="password_change"),
    path("me/phone/request/", views.phone_change_request, name="phone_change_request"),
    path("me/phone/confirm/", views.phone_change_confirm, name="phone_change_confirm"),
    path("me/metrics/<slug:metric_name>/", views.metric, name="metric"),
    path("me/dashboard/", views.dashboard, name="dashboard"),
    path("me/courses/", views.courses, name="courses"),
    path("me/orders/", views.orders, name="orders"),
    path("me/notifications/", views.notifications, name="notifications"),
    path("me/notifications/<int:pk>/read/", views.mark_notification_read, name="notification_read"),
    path("me/coach-requests/", views.coach_request, name="coach_request"),
    path("me/programs/", views.programs, name="programs"),
    path("me/programs/<int:pk>/performance/", views.program_performance, name="program_performance"),
    path("me/documents/<int:pk>/download/", views.document_download, name="document_download"),
    path("me/documents/<int:pk>/payment/", views.document_payment, name="document_payment"),
    path("courses/", views.series_list, name="series_list"),
    path("courses/<int:pk>/", views.series_detail, name="series_detail"),
    path("courses/<int:pk>/comments/", views.create_comment, name="create_comment"),
    path("courses/<int:pk>/comments/<int:comment_id>/replies/", views.create_reply, name="create_reply"),
    path("courses/<int:pk>/enroll/", views.enroll_free, name="enroll_free"),
    path("articles/", views.article_list, name="article_list"),
    path("articles/<slug:slug>/", views.article_detail, name="article_detail"),
    path("search/", views.search, name="search"),
    path("cart/", views.cart_detail, name="cart_detail"),
    path("cart/items/<int:pk>/", views.cart_add, name="cart_add"),
    path("cart/items/<int:pk>/delete/", views.cart_delete, name="cart_delete"),
    path("cart/empty/", views.cart_empty, name="cart_empty"),
    path("orders/", views.order_create, name="order_create"),
    path("orders/<int:pk>/discount/", views.order_discount, name="order_discount"),
    path("orders/<int:pk>/payment/", views.order_payment, name="order_payment"),
    path("payments/verify/", views.payment_verify, name="payment_verify"),
    path("payments/documents/verify/", views.document_payment_verify, name="document_payment_verify"),
    path("episodes/<int:pk>/video/", views.episode_video, name="episode_video"),
]
